server:
  port: 2333
  address: 61.1.230.195
  password: "ftunes"

lavalink:
  server:
    sources:
      youtube: false  # Disables old YouTube source
plugins:
  - dependency: "gg.amyassist.amy:lavalink-plugin-youtube:1.0.0"
